version: '3'

volumes:
  pgdata:

services:
  db:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_PASSWORD: project
      POSTGRES_USER: postgres
      POSTGRES_DB: project
    ports:
      - 5431:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

